import React from "react";
import { useState } from "react";
import Table from "../components/Table.jsx";
import SearchBar from "../components/SearchBar.jsx";
import { reports } from "../data/mock.js";

export default function Reports() {
  const [q, setQ] = useState("");
  const filtered = reports.filter(r => r.title.toLowerCase().includes(q.toLowerCase()));

  const columns = [
    { key: "id", title: "Report ID" },
    { key: "title", title: "Title" },
    { key: "range", title: "Range" },
    { key: "generatedBy", title: "Generated by" },
  ];

  return (
    <div>
      <div className="flex items-center gap-3 mb-3">
        <SearchBar value={q} onChange={setQ} placeholder="Search reports..." />
        <button className="btn-secondary">Generate new report</button>
      </div>
      <Table columns={columns} data={filtered} />
    </div>
  );
}
